-- =============================================
-- AJUSTES DE POLÍTICAS (RLS)
-- =============================================
-- Este archivo se deja intencionalmente vacío.
--
-- Toda la estructura principal de la base de datos,
-- incluyendo las políticas de seguridad iniciales,
-- se define en el archivo 'supabase_schema.sql'.
--
-- Usa este archivo solo para añadir pequeños ajustes
-- o políticas temporales si es necesario en el futuro.
-- =============================================